<?php

namespace Incept\Framework;

use PHPUnit\Framework\TestCase;
use UGComponents\Resolver\ResolverException;
use UGComponents\Package\Package;

Decorator::DECORATE;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Framework_Decorator_Test extends TestCase
{
  /**
   * @var Decorator
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers ::incept
   */
  public function testIncept()
  {
    $this->assertInstanceOf(FrameworkHandler::class, incept());
    $this->assertInstanceOf(Package::class, incept('event'));
    $this->assertEquals('foobar', incept(function() {
      return 'foobar';
    }));

    $trigger = false;
    try {
      incept('foobar');
    } catch(ResolverException $e) {
      $trigger = true;
    }

    $this->assertTrue($trigger);
  }
}
