<?php //-->
/**
 * This file is part of a package designed for the Incept Project.
 *
 * Copyright and license information can be found at LICENSE.txt
 * distributed with this package.
 */

namespace Incept\Framework\Validation;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Incept_Validation_ValidationRegistry_Test extends TestCase
{
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Incept\Framework\Validation\ValidatorRegistry::getValidator
   */
  public function testGetValidator()
  {
    $actual = new (ValidatorRegistry::getValidator('foo'));
    $this->assertInstanceOf(ValidatorInterface::class, $actual);
  }

  /**
   * @covers Incept\Framework\Validation\ValidatorRegistry::getValidators
   */
  public function testGetValidators()
  {
    $actual = ValidatorRegistry::getValidators();
    $this->assertTrue(is_array($actual));
  }

  /**
   * @covers Incept\Framework\Validation\ValidatorRegistry::makeValidator
   */
  public function testMakeValidator()
  {
    $actual = ValidatorRegistry::makeValidator('foo');
    $this->assertInstanceOf(ValidatorInterface::class, $actual);
  }

  /**
   * @covers Incept\Framework\Validation\ValidatorRegistry::register
   */
  public function testRegister()
  {
    $actual = ValidatorRegistry::register('foo::class');
    $this->assertFalse($actual);

    $actual = ValidatorRegistry::register(Required::class);
    $this->assertTrue($actual);
  }
}
