<?php

namespace Incept\Framework\Package\Config;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 11:36:33.
 */
class Framework_Config_ConfigException_Test extends TestCase
{
  /**
   * @var ConfigException
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new ConfigException;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Incept\Framework\Package\Config\ConfigException::forFileNotFound
   */
  public function testForFileNotFound()
  {
    $message = null;
    try {
      throw ConfigException::forFileNotFound('foo');
    } catch(ConfigException $e) {
      $message = $e->getMessage();
    }

    $this->assertEquals('File foo was not found', $message);
  }

  /**
   * @covers Incept\Framework\Package\Config\ConfigException::forFolderNotFound
   */
  public function testForFolderNotFound()
  {
    $message = null;
    try {
      throw ConfigException::forFolderNotFound('foo');
    } catch(ConfigException $e) {
      $message = $e->getMessage();
    }

    $this->assertEquals('Folder foo was not found', $message);
  }

  /**
   * @covers Incept\Framework\Package\Config\ConfigException::forFolderNotSet
   */
  public function testForFolderNotSet()
  {
    $message = null;
    try {
      throw ConfigException::forFolderNotSet();
    } catch(ConfigException $e) {
      $message = $e->getMessage();
    }

    $this->assertEquals('Folder not set. Try $config->setFolder(string).', $message);
  }
}
