<?php

namespace Incept\Framework\Package\Host;

use StdClass;
use PHPUnit\Framework\TestCase;

use Incept\Framework\Framework;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Framework_Host_HostPackage_Test extends TestCase
{
  /**
   * @var EventPackage
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $handler = new Framework;
    $handler('config')->setFolder(dirname(dirname(__DIR__)) . '/assets/config');
    $this->object = new HostPackage($handler);

    $_SERVER['HTTP_HOST'] = 'foobar.com';
    $_SERVER['SERVER_PORT'] = 443;
    $_SERVER['REQUEST_URI'] = '/foo/bar/?foo=bar';
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::all
   */
  public function testAll()
  {
    $all = $this->object->all();
    $this->assertEquals('https://foobar.com/foo/bar', $all['base']);
    $this->assertEquals('/foo', $all['dir']);
    $this->assertEquals('foobar.com', $all['domain']);
    $this->assertEquals('https://foobar.com', $all['name']);
    $this->assertEquals('/foo/bar', $all['path']);
    $this->assertEquals('/foo/bar?foo=bar', $all['relative']);
    $this->assertEquals('https://foobar.com/foo/bar?foo=bar', $all['url']);
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::base
   */
  public function testBase()
  {
    $this->assertEquals('https://foobar.com/foo/bar', $this->object->base());
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::dir
   */
  public function testDir()
  {
    $this->assertEquals('/foo', $this->object->dir());
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::domain
   */
  public function testDomain()
  {
    $this->assertEquals('foobar.com', $this->object->domain());
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::name
   */
  public function testName()
  {
    $this->assertEquals('https://foobar.com', $this->object->name());
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::path
   */
  public function testPath()
  {
    $this->assertEquals('/foo/bar', $this->object->path());
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::relative
   */
  public function testRelative()
  {
    $this->assertEquals('/foo/bar?foo=bar', $this->object->relative());
  }

  /**
   * @covers Incept\Framework\Package\Host\HostPackage::url
   */
  public function testUrl()
  {
    $this->assertEquals('https://foobar.com/foo/bar?foo=bar', $this->object->url());
  }
}
