<?php //-->
/**
 * This file is part of a package designed for the Incept Project.
 *
 * Copyright and license information can be found at LICENSE.txt
 * distributed with this package.
 */

namespace Incept\Framework\Field;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class Incept_Field_Created_Test extends TestCase
{
  /**
   * @var Created
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp(): void
  {
    $this->object = new Created;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown(): void
  {
  }

  /**
   * @covers Incept\Framework\Field\Created::prepare
   */
  public function testPrepare()
  {
    $actual = $this->object->prepare('bar', 'foo', ['foo' => 'bar']);
    $this->assertStringContainsString(date('Y-m'), $actual);
  }

  /**
   * @covers Incept\Framework\Field\Created::render
   */
  public function testRender()
  {
    $actual = $this->object->render('bar', 'foo', ['foo' => 'bar']);
    $this->assertNull($actual);
  }
}
