<?php //-->
/**
 * This file is part of a package designed for the Incept Project.
 *
 * Copyright and license information can be found at LICENSE.txt
 * distributed with this package.
 */

namespace Incept\Framework\Field;

use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-27 at 13:49:45.
 */
class FieldRegistryTest extends TestCase
{
  /**
   * @covers Incept\Framework\Field\FieldRegistry::getField
   */
  public function testGetField()
  {
    $actual = new (FieldRegistry::getField('foo'));
    $this->assertInstanceOf(FieldInterface::class, $actual);
  }

  /**
   * @covers Incept\Framework\Field\FieldRegistry::getFields
   */
  public function testGetFields()
  {
    $actual = FieldRegistry::getFields();
    $this->assertTrue(is_array($actual));
  }

  /**
   * @covers Incept\Framework\Field\FieldRegistry::makeField
   */
  public function testMakeField()
  {
    $actual = FieldRegistry::makeField('foo');
    $this->assertInstanceOf(FieldInterface::class, $actual);
  }

  /**
   * @covers Incept\Framework\Field\FieldRegistry::register
   */
  public function testRegister()
  {
    $actual = FieldRegistry::register('foo::class');
    $this->assertFalse($actual);

    $actual = FieldRegistry::register(Active::class);
    $this->assertTrue($actual);
  }
}
